### PR TITLE
Fix Linear Map for Cargo 1.71

### PR DESCRIPTION
**Pull request by AdinAck**
## Motivation

In the latest version of Cargo the implementation of `Drop` for linear map does not compile.

## Changes

Revert `Drop` impl to previous implementation.

### CODE REVIEW

**Comment by birkenfeld** [comment]
This patch isn't correct. Like the new code says, `Vec` already implements `Drop`, so your change will call `drop()` twice on the contents. Look at this example:

```rust
struct S;

impl Drop for S {
    fn drop(&mut self) {
        println!("dropped an S");
    }
}

fn main() {
    let mut v = heapless::LinearMap::<&str, S, 5>::new();
    v.insert("a", S).ok().unwrap();
}
```

It will print "dropped an S" twice with the PR.

Just removing the `drop(&self.buffer)` is enough.

**Comment by AdinAck** [comment]
I did notice it continued to work when the entire `Drop` impl was removed, didn't realize it *actually* is not necessary. I will just remove it then, thanks.

**Comment by newAM** [comment]
There seems to be something wrong with the commits here, perhaps a `git revert` gone wrong?

I made a separate PR to fix in #388

**Comment by AdinAck** [comment]
cool yeah this PR desperately needed a rebase

**Comment by Dirbaio** [comment]
fixed in #388

**Pull request closed without merging**
