### PR TITLE
Add `recent_index`, `oldest_index`, `oldest,` and `is_filled` to HistoryBuffer API

### PR DESCRIPTION
**Pull request by YuhanLiin**
I added some convenience methods to the HistoryBuffer API to help keep track of both ends of the buffer.

### CODE REVIEW

**Comment by pleepleus** [comment]
I was just about to fork this repo because I needed these.  I will be happy to review.

**Review by pleepleus — CHANGES_REQUESTED** [review]
The code changes themselves look excellent.  In fact I already pointed my project to this commit because I needed the "oldest()" api and it passes my application tests.

Before this can be merged though it should:

1.  Refresh with a merge from main
2.  Modify the changelog with a note on the additions

**Review by newAM — CHANGES_REQUESTED** [review]
Sorry for the slow review!  Life has been keeping me busy lately.

**Comment by newAM** [comment]
Thanks for making the change!

I took a closer look before merging, and I have one last question (sorry!).  What is the use-case of the `_index` methods being public?  That seems like an implementation detail.

**Comment by YuhanLiin** [comment]
The index methods can be used with `as_slice` (which also seems like an implementation detail) to do indexing operations relative to the head and tail indices.

**Review by newAM — APPROVED** [review]
Thanks for adding this!  Sorry it took so long to get it merged.

**Pull request merged**
